[package]
name = "ingram"
version = "0.1.0"
edition = "2021"
authors = ["YXL76 <chenxin.lan.76@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bootloader = "0.10"
qemu-exit = "3.0"
spin = "0.9"
uart_16550 = "0.2"
x86_64 = "0.14"

[profile.release]
lto = true
