name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: denoland/setup-deno@v1
        name: Install deno
        with:
          deno-version: vx.x.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
          key: ${{ runner.os }}-deno

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup nightly rust
        run: rustup default nightly

      - name: Add rust components
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add llvm-tools-preview

      - name: Build
        run: deno run --unstable --allow-all scripts/build.ts
